//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace route_model_docs
{
    using System;
    using System.Collections.Generic;
    
    public partial class dots
    {
        public int Id_dot { get; set; }
        public string address { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lan { get; set; }
        public int Path_FK { get; set; }
        public string traf_categ_price { get; set; }
    
        public virtual paths paths { get; set; }
    }
}
